export const ADD_ACTIONS = [
  "CUSTOMER_CREATED", "SUPPLIER_CREATED", "PRODUCT_CREATED", "IMEI_CREATED", "IMEI_BATCH_CREATED",
  "BRANCH_CREATED", "VEHICLE_CREATED", "SIM_CREATED", "SIM_BATCH_CREATED", "RETURN_CREATED",
  "SALE_CREATED", "PURCHASE_RECEIVED", "PAYMENT_RECORDED", "USER_CREATED",
  "WARRANTY_CLAIM_CREATED", "RMA_CREATED", "INSTALLATION_SCHEDULED", "FILE_UPLOADED",
];

export const DELETE_ACTIONS = [
  "CUSTOMER_DELETED", "SUPPLIER_DELETED", "PRODUCT_DELETED", "USER_DELETED", "BRANCH_DELETED",
  "VEHICLE_DELETED", "SIM_DELETED", "SALE_DELETED", "PURCHASE_DELETED", "PAYMENT_DELETED",
  "IMEI_DELETED", "RETURN_DELETED", "WARRANTY_CLAIM_DELETED", "RMA_DELETED",
  "INSTALLATION_DELETED", "FILE_DELETED",
];
